"""third migration

Revision ID: 205b36a49e76
Revises: 8fe144f92d81
Create Date: 2023-10-23 20:57:11.689257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '205b36a49e76'
down_revision = '8fe144f92d81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenditures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expenditures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expenditures_name'), ['name'], unique=False)

    op.create_table('goal_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_goal', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incomes', schema=None) as batch_op:
        batch_op.drop_index('ix_incomes_name')
        batch_op.create_index(batch_op.f('ix_incomes_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incomes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incomes_name'))
        batch_op.create_index('ix_incomes_name', ['name'], unique=False)

    op.drop_table('goal_class')
    with op.batch_alter_table('expenditures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expenditures_name'))

    op.drop_table('expenditures')
    # ### end Alembic commands ###
